version: '3'

services:

################################
# Setup server container
################################
  server:
    build: src/server/
    expose:
      - "8080"
    ports: 
      - 8080:8080
    command: yarn dev

################################
# Setup client container
################################
  client:
    build: src/client/
    expose:
      - "3000"
    ports: 
      - 3000:3000
    links:
      - server
    command: yarn start
